name = "youtube-cf"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = ".next"

[site]
bucket = ".next"

[build.upload]
format = "service-worker"

[[routes]]
pattern = "/api/*"
script = "api/[[route]].js"

[env.production]
vars = { 
  YOUTUBE_API_KEY = "",
  CLOUDFLARE_COMPATIBILITY_FLAG = "nodejs_compat"
} 