name = "youtube-cf"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[routes]]
pattern = "/api/*"
script = "functions/[[routes]].js"

[site]
bucket = ".next"

[env.production]
vars = { YOUTUBE_API_KEY = "your_api_key" } 