name = "youtube-cf"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = ".next"

[site]
bucket = ".next"

[build.upload]
format = "service-worker"

[[routes]]
pattern = "/api/*"
script = "functions/[[routes]].js"

[env.production]
vars = { YOUTUBE_API_KEY = "your_actual_api_key" }

[env.production.build]
command = """
echo "Checking environment variables..."
if [ -z "$YOUTUBE_API_KEY" ]; then
  echo "Error: YOUTUBE_API_KEY is not set!"
  exit 1
fi
npm run build
""" 